/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.*/
#include <stdio.h>
#include <math.h>
int main()
{
   long long i,a=1,b=2;
   long long term,sum=0,n=4000000;
     while(a<=n)
       {
       	 term=a;
       	 a=b;
       	 b+=term;
       	  if(term%2==0)
			{
			  sum+=term;	
			} 
	   }
	  printf("\nThe summation of even terms in fbonacci series less than 4M is \n sum=%lld",sum);
return 0;
}
